### ISSUE TITLE
500 page limit?

### ISSUE THREAD

**Issue by ghost** [MrMaurice211/WikiaCrawler#1]
I'm trying to get the images from the [Slay the Spire wiki](https://slay-the-spire.fandom.com/) which at the time of me writing this has 746 pages, but the program only says it finds 500 pages. Some of the images are definitely missing after I download them all.

Thanks for the program! Saved me a lot of time regardless.

**Comment by MrMaurice211** [comment]
Hey there! Glad it was useful, may it is a api rate limit, let do a check for that!

**Comment by MrMaurice211** [comment]
> I'm trying to get the images from the [Slay the Spire wiki](https://slay-the-spire.fandom.com/) which at the time of me writing this has 746 pages, but the program only says it finds 500 pages. Some of the images are definitely missing after I download them all.
> 
> Thanks for the program! Saved me a lot of time regardless.

This should be fixed now, let me know if you find any other issue!
